# Generated by Django 5.0.3 on 2024-04-27 21:48

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Avis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pseudo', models.CharField(max_length=50)),
                ('commentaire', models.TextField()),
                ('isVisible', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50)),
                ('prenom', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('message', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Habitat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('commentaire_habitat', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Race',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Animal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prenom', models.CharField(max_length=50)),
                ('etat', models.CharField(max_length=50)),
                ('image', models.ImageField(upload_to='animals/', verbose_name="Image de l'animal")),
                ('habitat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='animaux', to='liste.habitat')),
                ('race', models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='animaux', to='liste.race')),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_data', models.ImageField(upload_to='images/')),
                ('animal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='liste.animal')),
                ('habitat', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='liste.habitat')),
            ],
        ),
        migrations.CreateModel(
            name='RapportVeterinaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('detail', models.TextField()),
                ('animal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rapports_veterinaires', to='liste.animal')),
            ],
        ),
        migrations.CreateModel(
            name='NourritureInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nourriture_proposee', models.CharField(max_length=255, verbose_name='Nourriture proposée')),
                ('grammage_nourriture', models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='Grammage de la nourriture')),
                ('date_consommation', models.DateField(default=django.utils.timezone.now, verbose_name='Date de consommation')),
                ('heure_consommation', models.TimeField(default=django.utils.timezone.now, verbose_name='Heure de consommation')),
                ('rapport', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nourriture_infos', to='liste.rapportveterinaire')),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=200)),
                ('heure_ouverture', models.TimeField(blank=True, null=True, verbose_name="Heure d'ouverture")),
                ('heure_fermeture', models.TimeField(blank=True, null=True, verbose_name='Heure de fermeture')),
                ('roles', models.ManyToManyField(related_name='services', to='liste.role')),
            ],
        ),
        migrations.CreateModel(
            name='Utilisateur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50, unique=True)),
                ('password', models.CharField(max_length=50)),
                ('nom', models.CharField(max_length=50)),
                ('prenom', models.CharField(max_length=50)),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='utilisateurs', to='liste.role')),
            ],
        ),
    ]
