# Generated by Django 5.0.3 on 2024-05-02 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('liste', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='animal',
            name='clics',
            field=models.IntegerField(default=0),
        ),
    ]
