# Generated by Django 5.0.6 on 2024-05-13 21:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('liste', '0002_animal_clics'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nourritureinfo',
            name='rapport',
        ),
        migrations.AddField(
            model_name='nourritureinfo',
            name='animal',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='nourriture_infos', to='liste.animal'),
            preserve_default=False,
        ),
    ]
